# Generated by Django 5.2.3 on 2025-06-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='employee_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
