# Generated by Django 5.2.3 on 2025-06-24 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_employee_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
