# Generated by Django 5.2.3 on 2025-06-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='employee',
        ),
    ]
